name: Prepare
description: Prepare test environment
runs:
  using: composite
  steps:
    - name: Download node artifact
      uses: actions/download-artifact@v4
      with:
        name: ink-node
        path: ./

    - name: Start local node
      shell: bash
      run: |
        tar -xvzf ink-node-linux.tar.gz
        cd ink-node-linux/ 
        chmod +x ./ink-node
        ./ink-node --dev &